### ISSUE TITLE
Skipping unknown lines?

### ISSUE THREAD

**Issue by 8176135** [snylonue/cuna#3]
I am getting an error like the following:
```
 Error { error: UnexpectedToken("FLAGS"), at: Some(11) }
```

Is there any way to skip unknown tokens? Or a general way to skip past error lines?

**Comment by snylonue** [comment]
If you have a `string` or `&str`, try [`Parna`](https://docs.rs/cuna/0.6.0/cuna/parser/struct.Parna.html)
If you are reading from a file, there is not a convenient way, but you can try the function below(not tested):
``` rust
use cuna::Cuna;
use cuna::parser::Command;
use std::path::Path;
use std::io::BufRead;
use std::io::BufReader;
use std::io::Result;
use std::fs::File;

pub fn from_buf_read_ignore_error(buf: &mut impl BufRead) -> Result<Cuna> {
    let mut sheet = Cuna::default();
    let mut buffer = String::new();
    loop {
        match buf.read_line(&mut buffer)? {
            0 => break Ok(sheet),
            _ => {
                let command = match Command::new(cuna::trim_utf8_header(&buffer)) {
                    Ok(cmd) => cmd,
                    _ => continue,
                };
               let _ = command.parse(&mut sheet);
            }
        }
        buffer.clear();
    }
}
fn read_ignore_error(path: impl AsRef<Path>) -> Result<Cuna> {
    let file = File::open(path)?;
    let mut buf = BufReader::new(file);
    from_buf_read_ignore_error(&mut buf)
}

fn main() {
    println!("{:?}", read_ignore_error(r"path/to/file"));
    println!("{:?}", Cuna::open(r"/path/to/file"));
}
```

**Comment by 8176135** [comment]
Thanks.

It wasn't clear from the documentation how to use Parna. I ended up with the following;

```
	let mut parser = cuna::parser::Parna::new(&data);

	let mut cue_file = cuna::Cuna::default();
	while parser.current_line().is_some() {
		parser.parse(&mut cue_file).ok();
	}
```

Which seems to work. Is this the intended way to use Parna (e.g. is parse moving to the next line on failure intended)?

**Comment by snylonue** [comment]
> is parse moving to the next line on failure intended

Yes.

But actually I did't think of the exact way to use `Parna`. Do you have any suggestion?

By the way, a new constructive method which ignores parser errors will be implemented on `Cuna` in future versions.

**Comment by 8176135** [comment]
Since my current use case is to just parse a bunch of mostly valid cue files for some common tokens and don't mind ignoring everything else, having functionality similar to `rcue`'s https://gyng.github.io/rcue/rcue/parser/fn.parse_from_file.html `strict = false` directly on Cuna would be more than enough.

As for `Parna`, one of the main confusions when I tried to use it was where to put the actual string, inside the `Parna` constructor, or in `Cuna`'s constructor? What if there is data in both? 

If I understand correctly, `Cuna` contains the parsed data, and `Parna` is the parser, so maybe either:

1. Not allow constructing `Cuna` directly with a string, but only with a `Parna`, with has the string.
2. Or just rename the `Cuna::new()` to something else, like `Cuna::parse`, with comments describing how this is different from using Parna.

**Comment by snylonue** [comment]
> 
> 
> Thanks.
> 
> It wasn't clear from the documentation how to use Parna. I ended up with the following;
> 
> ```
> 	let mut parser = cuna::parser::Parna::new(&data);
> 
> 	let mut cue_file = cuna::Cuna::default();
> 	while parser.current_line().is_some() {
> 		parser.parse(&mut cue_file).ok();
> 	}
> ```
> 
> Which seems to work. Is this the intended way to use Parna (e.g. is parse moving to the next line on failure intended)?

You just need to call parse() until Ok(()) is returned
